### ISSUE TITLE
 Speed Boost

### ISSUE THREAD

**Issue by GodLea** [MrSonicMaster/vHackXT-MoneyBot#9]
you can increase the speed of the bot attack?
Another error returned was:
some player does not make the initial login, even if the data is correct.

I congratulate you for the work you've done ^-^

**Comment by MrSonicMaster** [comment]
It is already an option to change the delay between actions, go into the vHack.js and look in the constructor where it defines this.delayBetweenActions to a value. Lowering the value will cause the bot to run faster, but might cause the bot to not function as well because their NGINX server where the API is hosted has spam protection. If you need further help on how to do this, comment back. If you do what you intended to do successfully, please close the issue.
